### ISSUE TITLE
Error while generating in cmake in Windows

### ISSUE THREAD

**Issue by lokitkhemka** [PacktPublishing/3D-Graphics-Rendering-Cookbook#10]
While I am generating using cmake in Windows, I get the following error:

CMake Error at CMakeLists.txt:125 (set_property):
  set_property could not find TARGET zlibstatic.  Perhaps it has not yet been
  created.

I tried installing zlib using conda, but it is not working. Any help please? Thank you.

**Comment by lokitkhemka** [comment]
Now, I am getting new error: "Make sure Python can be started from the command line (add path to `python.exe` to PATH on Windows)". I already have python installed and added to PATH. The output of  "python --version" is "Python 3.9.12".

**Comment by corporateshark** [comment]
@lokitkhemka Are you running it from Conda or from native Windows? Only native Windows environment is supported on Windows.

**Comment by LLViktor** [comment]
Please, post your exact CMake command call.

Also, please, clarify what is your environment: MSys2 + Conda, Conda-only with internal GCC, some native GCC installation or Conda + MS Visual Studio.

Unfortunately, we only support clean system-wide installation of Python 3 + Microsoft Visual Studio, not some virtual_environment based on conda. Basically, our Python script downloads all required C and C++ _sources_ (not some precompiled libraries, as Conda does) for the libraries and creates a .sln/.vcxproj files for Visual Studio which builds the entire project.

The book is all about native C++ development (so no WSL, no Conda), Python scripts are for your convenience only (while downloading the C/C++ libraries). So, please, follow the official guide presented in the book:

a) Install Python 3
b) Install Visual Studio
c) Install CMake
d) Install git, mercurial etc. (other dependencies)

Then run 'bootstrap.py' script and finally runcmake -G "Visual Studio 17 2022"

**Comment by lokitkhemka** [comment]
I solved it by running `python3 bootstrap.py` from WSL because for some reason I was unable to run the command on my windows. Then, I used cmake to generate the project files and build them in Windows.
