### ISSUE TITLE
Vector * Matrix vs Matrix * Vector

### ISSUE THREAD

**Issue by zixin96** [PacktPublishing/3D-Graphics-Rendering-Cookbook#12]
https://github.com/PacktPublishing/3D-Graphics-Rendering-Cookbook/blob/86c2eed4b7853d21a667018b0a21ece3dbf9e900/data/shaders/chapter03/GL03_duck.vert#L38-L39

I am a bit confused about why we use `vector * matrix` order in the first line and `matrix * vector` in the second line. In GLSL, they give [different ](https://en.wikibooks.org/wiki/GLSL_Programming/Vector_and_Matrix_Operations#Operators) results. 

I think it should be changed to ` vtx.normal = normalMatrix * getNormal(gl_VertexID);`.  

Thanks!

**Comment by corporateshark** [comment]
That `transpose()` in the previous line should compensate for that.
