### ISSUE TITLE
Can't compile on OSX

### ISSUE THREAD

**Issue by ibesora** [PacktPublishing/3D-Graphics-Rendering-Cookbook#14]
Running 
```
cmake .. -G "Unix Makefiles"
cmake --build . --config Release
```
Results in the following error while compiling ImGuizmo
```
3D-Graphics-Rendering-Cookbook/deps/src/ImGuizmo/ImGuizmo.cpp:2546:21: error: expected ';' at end of declaration
      bool boxes[27]{};
```

Generating an XCode project with `cmake .. -G "Xcode"`, opening the XCode project and compiling gives the same error

I think both of them come from the fact that CLang 13 has partial support for C++20

Installing GCC 12 and forcing it's usage with 
```
CC=gcc-12 CXX=gcc-12 cmake .. -G "Unix Makefiles"
cmake --build . --config Release
```
shows the following error when linking EtcLib

```
ld: symbol(s) not found for architecture arm64
```

Just wondering if someone had any luck at compiling the project

**Comment by corporateshark** [comment]
Does it work with the latest version of [ImGuizmo](https://github.com/CedricGuillemet/ImGuizmo)?

**Comment by ibesora** [comment]
I've tried some new things:
The first problem, the one related to ImGuizmo seems to be related to Apple's CLANG not having support for C+++20, I have been able to do a successful compile of the project with GCC 12 and with a homebrew version of CLANG

Now, running
```
CC=clang CXX=clang++ cmake .. -G "Unix Makefiles"
cmake --build . --config Release
```
fails with the following error
```
Chapter7/SceneConverter/src/main.cpp:510:22: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
        std::transform(std::execution::par, std::begin(files), std::end(files), std::begin(files), converter);
```
which seems weird to me because CLANG is version 14 and that's supposed to support all the C++17 spec which is the one that includes std::execution.

Trying to compile it with GCC via 
```
CC=gcc-12 CXX=g++-12 cmake .. -G "Unix Makefiles"
cmake --build . --config Release
```
fails to link EtcTool with
```
from /Users/ibesora/workspace/3D-Graphics-Rendering-Cookbook/deps/src/glfw/src/context.c:30:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:391:15: error: expected identifier or '(' before '^' token
  391 | typedef void (^CGPathApplyBlock)(const CGPathElement * element);
      |               ^
```
This looks to me like it's trying to use Xcode headers. GCC is configured with `--with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk` so it makes sense that it tries to use those headers.

I'm sorry but I'm quite new to the macOS build tooling

**Comment by corporateshark** [comment]
Apple Clang support of C++20 is complete. There must be some issues with your configuration. Unfortunately, I cannot reproduce the issue locally.

**Comment by ibesora** [comment]
> Apple Clang support of C++20 is complete. 

Sorry if I'm wrong, I was taking [this C++20 support table](https://en.cppreference.com/w/cpp/compiler%20support#cpp20) and it says it isn't.
Also, according to the [C++17 table](https://en.cppreference.com/w/cpp/compiler_support/17), parallel algorithms and execution policies is also not supported, which looks reasonable with what I'm seeing (`std::execution::par` not found when compiling with Xcode)

> There must be some issues with your configuration. Unfortunately, I cannot reproduce the issue locally.

There might be! Unfortunately even if I were to solve those issues, I realized I wouldn't be able to get OpenGL 4.6 to work in my Macbook Air M1 because it's only supporting 4.1 so I suppose I'm going to use my Windows computer.

Thanks again for your help!
