### ISSUE TITLE
Question: Why normal matrix uses only inverted model matrix?

### ISSUE THREAD

**Issue by ivan-ushakov** [PacktPublishing/3D-Graphics-Rendering-Cookbook#15]
[Here](https://github.com/PacktPublishing/3D-Graphics-Rendering-Cookbook/blob/master/data/shaders/chapter06/GL01_PBR.vert):
```
void main()
{
	mat4 model = in_Model[gl_DrawID];
	mat4 MVP = proj * view * model;

	vec3 pos = getPosition(gl_VertexID);
	gl_Position = MVP * vec4(pos, 1.0);

	tc = getTexCoord(gl_VertexID);

	mat3 normalMatrix = transpose( inverse(mat3(model)) );

	normal = normalMatrix  * getNormal(gl_VertexID);
	worldPos = ( in_Model[gl_DrawID] * vec4(pos, 1.0) ).xyz;
}
```

Usually when you calculate normal matrix you need to use inverse of view model matrix.

**Comment by corporateshark** [comment]
https://computergraphics.stackexchange.com/questions/1502/why-is-the-transposed-inverse-of-the-model-view-matrix-used-to-transform-the-nor

**Comment by ivan-ushakov** [comment]
> https://computergraphics.stackexchange.com/questions/1502/why-is-the-transposed-inverse-of-the-model-view-matrix-used-to-transform-the-nor

But this does not answer why you use only model matrix not modelView matrix

**Comment by corporateshark** [comment]
The matrix used is the matrix which transforms from the model space to the space in which the lighting is calculated. We do all lighting in world-space, hence we use the model-to-world matrix to bring everything in the same space.
