### ISSUE TITLE
data/shaders/chapter06/imgui_multi.frag missing?

### ISSUE THREAD

**Issue by tuket** [PacktPublishing/3D-Graphics-Rendering-Cookbook#19]
Is this file missing?

![image](https://user-images.githubusercontent.com/4165974/197533209-00a04234-3bcd-4b57-83c7-087285be3919.png)

I'm just browsing the repo with the online VSCode. Not sure if that file is downloaded by the bootstrap.py script. I didn't want to download 15GB...

**Comment by LLViktor** [comment]
Yes, you are right. The file is missing (actually, it was renamed during refactoring), this is our mistake. Here you can use the "shaders/chapter07/VK02_ImGui.frag" file instead. This code path (in vkRenderers subfolder) is intended for first few chapters only, so we missed this issue during the vkFramework folder development (but the shader code itself remains unchanged).

**Comment by LLViktor** [comment]
Same thing with .vert shader - you can use VK02_ImGui.vert from chapter07 folder.
