### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by gituser1024** [PacktPublishing/3D-Graphics-Rendering-Cookbook#2]
missing data/meshs/*

bistro_all.materials
bistro_all.meshes
bistro_all.scene
test.materials
test.meshes
test.scene
test.meshes.instances
test_graph.materials
test_graph.meshes
test_graph.scene
test2.materials
test2.meshes
test2.scene
cube.material
cube.meshes
cube.scene
test.boxes
test_graph.boxes
test2.boxes
test.meshes.drawdata
test_duck.materials
test_duck.meshes
test_duck.scene

**Comment by corporateshark** [comment]
You have to run the `Chapter7/SceneConverter` tool to generate these files.
