### ISSUE TITLE
Renderer pattern design question

### ISSUE THREAD

**Issue by YTN0** [PacktPublishing/3D-Graphics-Rendering-Cookbook#21]
Just purchased a copy of this book and am reading through it. Really like the structure of the book and content, however I have a question about the renderer concept and design that's used in the book. 

The book describes the different renderers and how to leverage that pattern. It also describes using the frustum to cull by turning off geometry by setting the instance count to 0.

That works fine for a geometry & textures that fit on the GPU, however, how can the renderer pattern be used for a very large landscape with lots of trees etc.? I have a quadtree for culling, and can't seem to find a way to fit that into the pattern.

Ideally, I'd want to leverage the quadtree for culling, and be able to stream geometry (and textures) into and out of the GPU based on some algorithm based on the camera and distance.

Any suggestions on how the renderer pattern could be modified for that?

Thanks!

**Comment by corporateshark** [comment]
Hello!

Our book provides some insights into various rendering techniques, but its focus is primarily on these techniques and not on the overall design and high-level features of a generic 3D gaming engine. The book provides a solid foundation for understanding how to create efficient renderers, but it is not intended to be a comprehensive guide for creating a complete gaming engine that can handle large and complex landscapes.

Maybe "Game Engine Architecture" by Jason Gregory can give you more insights into your question.

**Comment by Dunk-Master** [comment]
https://github.com/KhronosGroup/KTX-Software is there any reason you didn't use this? why etc2comp

**Comment by corporateshark** [comment]
Only for historical reasons. Basis compression was not in KTX in 2019.
