### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by erikmartinessanches** [PacktPublishing/3D-Graphics-Rendering-Cookbook#22]
Now that [MoltenVK](https://github.com/KhronosGroup/MoltenVK/blob/main/Docs/MoltenVK_Runtime_UserGuide.md#limitations) supports Vulkan 1.2, is it feasible to use this book with macOS?

**Comment by corporateshark** [comment]
Yes, it should be technically possible to run the code with MoltenVK. Enabling `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` is necessary.
