### ISSUE TITLE
data/meshes directory is missing assets

### ISSUE THREAD

**Issue by kyamant** [PacktPublishing/3D-Graphics-Rendering-Cookbook#26]
for example Ch8_SampleGL02_SSAO needs
GLSceneData sceneData1("data/meshes/test.meshes", "data/meshes/test.scene", "data/meshes/test.materials");
	GLSceneData sceneData2("data/meshes/test2.meshes", "data/meshes/test2.scene", "data/meshes/test2.materials");
none of them are there.

**Some QA before publishing please, I did not buy your to debug your build process!**

**Comment by corporateshark** [comment]
You need to run `Ch7_SceneConverter` before going to further demos. It will generate all the necessary files.

**Comment by LLViktor** [comment]
We are sorry for the inconvenience, but please try to understand the build process. These files are generated using the tools developed in the book. The decision to omit those (rather large) files is deliberate and it forces you to run the converter program first. When you try to run the samples from Chapter 7, 8 or 9, then the error message is displayed in a console telling you to run the Ch7_SceneConverter before running any demos.
