### ISSUE TITLE
LOD array indexing

### ISSUE THREAD

**Issue by ben-rampel** [PacktPublishing/3D-Graphics-Rendering-Cookbook#28]
1) The LOD generation code can create up to 8 LODs
2) Mesh::lodOffset is defined with size 8
3) Mesh::getLODIndicesCount(uint32_t lod) references lodOffset[lod+1]
So, getting the number of indices in your 8th LOD is not defined.
This can cause problems trying to merge scenes considering all LODs.

**Comment by corporateshark** [comment]
@ben-rampel Thanks for pointing this out!

As the book does not actually use LODed rendering, the issue remains. I've added an `assert` to highlight the problem.

We are working on the next edition and will rework many things related to LODs.
