### ISSUE TITLE
[BUG] Dec 2024 Generated Volk Files are Outdated : 3D Graphics Rendering Cookbook 

### ISSUE THREAD

**Issue by yeokaiwei** [PacktPublishing/3D-Graphics-Rendering-Cookbook#31]
Hi Sergey,
The Volk files that are generated using Python and CMake are currently outdated in this version.

The error occurs in Chapter 03.

This will result in "function pointers but with a different define structure."

The latest version of volk.c and volk.h are in https://github.com/zeux/volk.

Thank you.

**Comment by corporateshark** [comment]
Fixed in https://github.com/PacktPublishing/3D-Graphics-Rendering-Cookbook/commit/819bebc8f5909007e5805e65581a7993e52f3221
