### ISSUE TITLE
[HELP] Building Chapter 03 :  3D-Graphics-Rendering-Cookbook

### ISSUE THREAD

**Issue by yeokaiwei** [PacktPublishing/3D-Graphics-Rendering-Cookbook#32]
Hi,
Could I request for some help to build Chapter 03?

I have received some peculiar linker errors.

In the Linker Input, I'm using "glfw3.lib, glslang.lib, SPIRV.lib, assimp-vc143-mt.lib, SharedUtils.lib, etc"

I have attached the .lib files that I am using but I have no idea why the linker is throwing an error.

May I request for some help?

Thank you.

References
![image](https://github.com/user-attachments/assets/f9210a9f-b9e1-401c-961f-edb107e2f282)
[Chap03Lib.zip](https://github.com/user-attachments/files/18018914/Chap03Lib.zip)

**Comment by corporateshark** [comment]
All the required `.lib` files will be automatically generated during the build process. You don’t need to supply any custom `.lib` files, as they’re not guaranteed to work (you’d essentially be on your own if you try).

To build the project on Windows, simply run these commands:

```
mkdir build
cd build
cmake .. 
start RenderingCookbook.sln
```

**Comment by yeokaiwei** [comment]
> All the required `.lib` files will be automatically generated during the build process. You don’t need to supply any custom `.lib` files, as they’re not guaranteed to work (you’d essentially be on your own if you try).
> 
> To build the project on Windows, simply run these commands:
> 
> ```
> mkdir build
> cd build
> cmake .. 
> start RenderingCookbook.sln
> ```

Hi Sergey,
Thank you, it works now.

I think the above CMake instructions are not in the book.

There are 2 different sets of files.

The CMake build folder has the executables and .lib so it's much easier to run the examples.

The original files from Github will run into the above problems.

**Comment by corporateshark** [comment]
> I think the above CMake instructions are not in the book.
> There are 2 different sets of files.
> The CMake build folder has the executables and .lib so it's much easier to run the examples.
> The original files from Github will run into the above problems.

The CMake instructions are listed on the front page of [this repository](https://github.com/PacktPublishing/3D-Graphics-Rendering-Cookbook).

I just cloned the repository fresh from GitHub and followed all the steps locally. Everything compiled from scratch without any issues using Visual Studio 2022. Here are the exact commands I used to clone the repo, configure CMake, and open the project:

```
git clone https://github.com/PacktPublishing/3D-Graphics-Rendering-Cookbook.git 3D-Book
cd 3D-Book
bootstrap.py
mkdir build
cd build
cmake ..
start RenderingCookbook.sln
```

Everything went smoothly, with no compilation errors.

**Comment by yeokaiwei** [comment]
Hi @corporateshark,
Thanks.

Just giving a suggestion for your 2nd edition.

Some readers might miss the instructions as it's not in the book.
