### ISSUE TITLE
[FEEDBACK] Chapter 03 Cube Map : Sergey Kosarevsky (3D-Graphics-Rendering-Cookbook)

### ISSUE THREAD

**Issue by yeokaiwei** [PacktPublishing/3D-Graphics-Rendering-Cookbook#33]
Hi Sergey,
I triggered a strange error in Visual Studio 2022

This occurred when I opened Bitmap.h and wrote some notes in it.

I couldn't even save the file nor could I close Visual Studio 2022 normally.

I thought you would like to know about this.

> Error HRESULT E_FAIL has been returned from a call to a COM component

![Screenshot 2024-12-10 150810](https://github.com/user-attachments/assets/ef8e147c-03ee-475f-b9c9-4a12f844fa05)

**Comment by corporateshark** [comment]
I cannot reproduce it. It does not look specific to this repository.

**Comment by yeokaiwei** [comment]
Perhaps, this is due to a virus or a VS2022 update?

Thank you.
