### ISSUE TITLE
[FEEDBACK] Pg 103 Grammar? : Sergey Kosarevsky (3D-Graphics-Rendering-Cookbook)

### ISSUE THREAD

**Issue by yeokaiwei** [PacktPublishing/3D-Graphics-Rendering-Cookbook#34]
Hi Sergey,
I think there might a logical error on page 103.

"The zoffset parameter of the function is used to specify the i index of the face."

I think it should be reversed.

"The i index of the face is used to specify the z-offset parameter of the function."

**Comment by corporateshark** [comment]
Thanks!

It is fixed in the 2nd edition!
