### ISSUE TITLE
[FEEDBACK] Typo Pg 113 : Sergey Kosarevsky

### ISSUE THREAD

**Issue by yeokaiwei** [PacktPublishing/3D-Graphics-Rendering-Cookbook#36]
Hi Sergey,
Is there a mismatch between the book and the code?

Is VK_ASSERT supposed to be CHECK?

Pg 113, 

Book
```
static void VK_ASSERT(bool check) {
 if(!check)
 exit(EXIT_FAILURE);
}
```

Github Code
```
void CHECK(bool check, const char* fileName, int lineNumber)
{
	if (!check)
	{
		printf("CHECK() failed at %s:%i\n", fileName, lineNumber);
		assert(false);
		exit(EXIT_FAILURE);
	}
}
```

P.S. I think CHECK() might be missing an else statement. Someone mentioned that if you nest the CHECK like
if(!success)
 CHECK();
else
 ...

It would create an error.

Hope this helps.

Thank you.

**Comment by corporateshark** [comment]
Thanks!

It will be fixed in the 2nd edition.
