### ISSUE TITLE
[FEEDBACK] Small Typo : Sergey Kosarevsky

### ISSUE THREAD

**Issue by yeokaiwei** [PacktPublishing/3D-Graphics-Rendering-Cookbook#37]
Hi Sergey,
This is a small issue, additional 'final' that is missing in the book.

Book, 
`struct VulkanInstance`

Github
`struct VulkanInstance final`

Just letting you know.

There are multiple examples of the additional 'final' missing from the book.

**Comment by corporateshark** [comment]
Thanks!
