### ISSUE TITLE
[FEEDBACK] Page 139 copyBufferToImage() : Sergey Kosarevsky

### ISSUE THREAD

**Issue by yeokaiwei** [PacktPublishing/3D-Graphics-Rendering-Cookbook#38]
Hi Sergey,
Page 139, copyBufferToImage() is missing layercount and there are typos.
```
void copyBufferToImage(VulkanRenderDevice& vkDev, 
						VkBuffer buffer, 
						VkImage image, 
						uint32_t width, 
						uint32_t height, 
						uint32_t layerCount) <--Missing
```

The book states `.layerCount = 1`, instead of  `.layerCount = layerCount`.

**Comment by corporateshark** [comment]
The source code has been updated with bug fixes and changes that were made after the book review was completed.
