### ISSUE TITLE
Missing include directories

### ISSUE THREAD

**Issue by bc-nine** [PacktPublishing/3D-Graphics-Rendering-Cookbook#4]
After bootstrapping, running

C:\3D-Graphics-Rendering-Cookbook\Chapter5\GL01_Grid\build> cmake .. -G "Visual Studio 16 2019" -A x64

then

C:\3D-Graphics-Rendering-Cookbook\Chapter5\GL01_Grid\build> cmake --build . --config Release

yields:

C:\3D-Graphics-Rendering-Cookbook\Chapter5\GL01_Grid\src\main.cpp(5,10): fatal error C1083: Cannot open include file: 'shared/glFramework/GLFWApp.h': No such file or directory [C:\3D-Graphics-Rendering-Cookbook\Chapter5\GL01_Grid\build\Ch5_SampleGL01_Grid.vcxproj]

**Comment by corporateshark** [comment]
Make the `build` folder in the root folder of the repo.
```C:\3D-Graphics-Rendering-Cookbook\build>cmake .. -G "Visual Studio 16 2019" -A x64```
