### ISSUE TITLE
Problem building in build dir with cmake

### ISSUE THREAD

**Issue by EvanNibbe** [PacktPublishing/3D-Graphics-Rendering-Cookbook#5]
After following the procedure in README.md
mkdir build
cd build
cmake ..
I was told by the errors to do the following
sudo apt-get install mercurial
sudo apt-get install libxrandr-dev
sudo apt-get install libxinerama-dev
sudo apt-get install libxcursor-dev
Then, after trying cmake .. again, I got the following error that indicates that a file is missing:
CMake Error at CMake/CommonMacros.txt:35 (add_executable):
  Cannot find source file:

    /home/evannibbe/ComputerScience/ComputerGraphics/deps/src/etc2comp/EtcTool/EtcFile.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  Chapter2/08_ETC2Comp/CMakeLists.txt:7 (SETUP_APP)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

However, when I search for that file myself, I find it!
evannibbe@xxx:~/ComputerScience/ComputerGraphics/3D-Graphics-Rendering-Cookbook/deps/src/etc2comp/EtcTool$ ls
Args.txt             CMakeLists.txt   EtcComparison.cpp  EtcFile.h          EtcMemTest.cpp      EtcSourceImage.h  Makefile
CMakeFiles           EtcAnalysis.cpp  EtcComparison.h    EtcFileHeader.cpp  EtcMemTest.h        EtcTool.cpp
cmake_install.cmake  EtcAnalysis.h    EtcFile.cpp        EtcFileHeader.h    EtcSourceImage.cpp  EtcTool.h

This seems to mean that I must copy the deps folder one folder level upward (I just used ln -s 3D-Graphics-Rendering-Cookbook/deps ./deps with the current working directory one higher), which is annoying, but allows everything to work.

**Comment by EvanNibbe** [comment]
However, after I started make on the newly created Makefile from running cmake .. above, make terminated at 
Linking CXX executable ../../bin/Ch7_Tool01_SceneConverter
/usr/bin/ld: cannot find -ltbb
collect2: error: ld returned 1 exit status
make[2]: *** [Chapter7/SceneConverter/CMakeFiles/Ch7_Tool01_SceneConverter.dir/build.make:103: bin/Ch7_Tool01_SceneConverter] Error 1
make[2]: Leaving directory '/home/evannibbe/ComputerScience/ComputerGraphics/3D-Graphics-Rendering-Cookbook'
make[1]: *** [CMakeFiles/Makefile2:3250: Chapter7/SceneConverter/CMakeFiles/Ch7_Tool01_SceneConverter.dir/all] Error 2
make[1]: Leaving directory '/home/evannibbe/ComputerScience/ComputerGraphics/3D-Graphics-Rendering-Cookbook'
make: *** [Makefile:130: all] Error 2

Which means that the resulting binary files are:
~/ComputerScience/ComputerGraphics/3D-Graphics-Rendering-Cookbook/bin$ ls
Ch1_Sample2_CMake          Ch2_Sample08_ETC2Comp       Ch3_SampleVK02_DemoApp       Ch5_SampleVK01_MultiMeshDraw       Ch6_SampleVK05_PBR
Ch2_Sample01_GLFW          Ch2_Sample09_TaskFlow       Ch4_SampleGL01_Camera        Ch5_Tool05_MeshConvert             Ch6_Util01_FilterEnvmap
Ch2_Sample02_GLM           Ch2_Sample10_MeshOptimizer  Ch4_SampleGL02_FPS           Ch6_SampleGL01_PBR                 Ch7_SampleGL01_LargeScene
Ch2_Sample03_STB           Ch3_SampleGL01_APIWrapping  Ch4_SampleVK01_DemoApp       Ch6_SampleVK01_BRDF_LUT
Ch2_Sample04_ImGui         Ch3_SampleGL02_VtxPulling   Ch5_SampleGL01_Grid          Ch6_SampleVK02_DescriptorIndexing
Ch2_Sample05_EasyProfiler  Ch3_SampleGL03_CubeMap      Ch5_SampleGL02_Tessellation  Ch6_SampleVK03_ComputeTexture
Ch2_Sample07_AssImp        Ch3_SampleVK01_GLSLang      Ch5_SampleGL03_MeshRenderer  Ch6_SampleVK04_ComputeMesh

**Comment by LLViktor** [comment]
This is definitely a missing package problem.

The error
/usr/bin/ld: cannot find -ltbb

means that there is no Intel Thread Building Blocks library.

On Ubuntu/Debian it can be installed with the following command:

sudo apt install libtbb-dev

**Comment by LLViktor** [comment]
The error itself is due to the fact that this converter uses C++17/C++20 parallel STL algorithms (which can be disabled, so no TBB is required).

If for some reason the problem does not go away, the in the SceneConverter source code (function 'convertAndDownscaleAllTextures') the 'std::transform()' call should be without the first argument 'std::execution::par'.
This disales parallel processing and does not require the TBB to be linked.

**Comment by EvanNibbe** [comment]
However, after I started make on the newly created Makefile from running cmake .. above, make terminated at 
Linking CXX executable ../../bin/Ch7_Tool01_SceneConverter
/usr/bin/ld: cannot find -ltbb
collect2: error: ld returned 1 exit status
make[2]: *** [Chapter7/SceneConverter/CMakeFiles/Ch7_Tool01_SceneConverter.dir/build.make:103: bin/Ch7_Tool01_SceneConverter] Error 1
make[2]: Leaving directory '/home/evannibbe/ComputerScience/ComputerGraphics/3D-Graphics-Rendering-Cookbook'
make[1]: *** [CMakeFiles/Makefile2:3250: Chapter7/SceneConverter/CMakeFiles/Ch7_Tool01_SceneConverter.dir/all] Error 2
make[1]: Leaving directory '/home/evannibbe/ComputerScience/ComputerGraphics/3D-Graphics-Rendering-Cookbook'
make: *** [Makefile:130: all] Error 2

Which means that the resulting binary files are:
~/ComputerScience/ComputerGraphics/3D-Graphics-Rendering-Cookbook/bin$ ls
Ch1_Sample2_CMake          Ch2_Sample08_ETC2Comp       Ch3_SampleVK02_DemoApp       Ch5_SampleVK01_MultiMeshDraw       Ch6_SampleVK05_PBR
Ch2_Sample01_GLFW          Ch2_Sample09_TaskFlow       Ch4_SampleGL01_Camera        Ch5_Tool05_MeshConvert             Ch6_Util01_FilterEnvmap
Ch2_Sample02_GLM           Ch2_Sample10_MeshOptimizer  Ch4_SampleGL02_FPS           Ch6_SampleGL01_PBR                 Ch7_SampleGL01_LargeScene
Ch2_Sample03_STB           Ch3_SampleGL01_APIWrapping  Ch4_SampleVK01_DemoApp       Ch6_SampleVK01_BRDF_LUT
Ch2_Sample04_ImGui         Ch3_SampleGL02_VtxPulling   Ch5_SampleGL01_Grid          Ch6_SampleVK02_DescriptorIndexing
Ch2_Sample05_EasyProfiler  Ch3_SampleGL03_CubeMap      Ch5_SampleGL02_Tessellation  Ch6_SampleVK03_ComputeTexture
Ch2_Sample07_AssImp        Ch3_SampleVK01_GLSLang      Ch5_SampleGL03_MeshRenderer  Ch6_SampleVK04_ComputeMesh

**Comment by LLViktor** [comment]
Is the issue still unresolved or installing the Intel's TBB helps to resolve it ?

**Comment by corporateshark** [comment]
Closing this issue as there were no updates from the OP.
