### ISSUE TITLE
Cannot find OptickCored.dll

### ISSUE THREAD

**Issue by EdgeOfTheMoon** [PacktPublishing/3D-Graphics-Rendering-Cookbook#6]
I am relatively new to CMake. I have an issue with launching chapters related to Optick. When executing them, it throws an error saying that OptickCored.dll cannot be found.

I also tried with a simpler project. Here is the source tree:

- CMakeLists
- src
   - CMakeLists
   - main.cpp
-  optick

The first CMakeLists is:
`cmake_minimum_required(VERSION 3.7)

project( OptickTest )

set_property(GLOBAL PROPERTY USE_FOLDERS ON)

add_subdirectory(optick)
add_subdirectory(src)
`

and the one inside the src folder is:
`cmake_minimum_required(VERSION 3.7)

add_executable( OptickTest "main.cpp" )

target_link_libraries( OptickTest OptickCore )`

I could handle libraries such as GFLW, but this one gives me trouble. I don't understand why it cannot find the dll.

**Comment by corporateshark** [comment]
Putting `OptickCored.dll` into the same folder, where your demo `.exe` binaries reside, should resolve the issue. Or you can put `OptickCored.dll` into your `Windows\System32` folder and forget about it.
