### ISSUE TITLE
Black spot in PBR implementation

### ISSUE THREAD

**Issue by FlexW** [PacktPublishing/3D-Graphics-Rendering-Cookbook#7]
Thank you for this awesome book. I discovered this black spot in the PBR implementation and wonder what the cause is.

![Screenshot from 2022-02-27 20-37-29](https://user-images.githubusercontent.com/19961516/155897139-fa18312c-aaeb-494c-8842-cdaf93d7c81a.png)
![Screenshot from 2022-02-27 20-36-41](https://user-images.githubusercontent.com/19961516/155897140-c05931d7-6835-4e04-a247-8fc53ce04487.png)

It's present in the Vulkan and OpenGL implementation and was captured on an Nvidia GTX 1060 on Linux.

Just for the record:
Seems to be fixed with this change in the `PBR.sp` shader
```glsl
vec2 brdfSamplePoint = clamp(vec2(pbrInputs.NdotV, 1.0 pbrInputs.perceptualRoughness), vec2(0.001, 0.001), vec2(0.009, 0.009));

```

**Comment by corporateshark** [comment]
A correct solution would be to set to `texBRDF_LUT` to a proper clamping mode `VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE`.
