### ISSUE TITLE
glx failed to create context glxbadfbconfig in ubuntu 21.04

### ISSUE THREAD

**Issue by minsoo5403** [PacktPublishing/3D-Graphics-Rendering-Cookbook#9]
Can't i use it on Ubuntu 21.04?

**Comment by corporateshark** [comment]
Yes. You need to install LunarG VulkanSDK for Linux: https://vulkan.lunarg.com/sdk/home#linux

Release 1.3.211 supports Ubuntu 20.04.

**Comment by LLViktor** [comment]
This error might not be Ubuntu-related, you need to check your graphics drivers and the output from 'glxinfo' tool. Most likely, your driver does not support OpenGL 4.5 which is strictly required by these samples.

Please, specify the exact demo which outputs this error and also, if possible, provide information about your graphics hardware. For example, an old Intel HD card on a laptop is not enough for running these demos. You can use the 'glxinfo' tool to print out all the relevant information.

**Comment by minsoo5403** [comment]
I was using xrdp with Ubuntu Linux 21.04 on Windows 10.

xrdp was caused by not supporting OpenGL 4.6.

If you run it locally, it works. Thank you.

**Comment by LLViktor** [comment]
Thank you for clarifying this issue )  We have not checked these samples using WSL in Windows 10, only natively on Windows and on Linux (Ubuntu 19.10/20.04).
